//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemInventory_Customer
    {
        public int ID { get; set; }
        public string ItemCode { get; set; }
        public string ItemSKUCode { get; set; }
        public int CustomerID { get; set; }
        public int WarehouseCode { get; set; }
        public string LocationID { get; set; }
        public string UOM { get; set; }
        public string LotCode { get; set; }
        public string SubLotCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> AvailableQuantity { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<int> PhysicalQuantity { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblItemMaster tblItemMaster { get; set; }
        public virtual tblItemSKUMaster tblItemSKUMaster { get; set; }
        public virtual tblLocation tblLocation { get; set; }
        public virtual tblWarehouseMaster tblWarehouseMaster { get; set; }
    }
}
