//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemSKUMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblItemSKUMaster()
        {
            this.tblItemInventory_Customer = new HashSet<tblItemInventory_Customer>();
        }
    
        public string ItemSKUCode { get; set; }
        public string ItemCode { get; set; }
        public string UPC { get; set; }
        public string UOM { get; set; }
        public string UOMAbbreviation { get; set; }
        public Nullable<double> InnerPackQuantity { get; set; }
        public Nullable<int> CasePack { get; set; }
        public Nullable<int> Tie { get; set; }
        public string High { get; set; }
        public string NMFC { get; set; }
        public string LTLClass { get; set; }
        public string TLClass { get; set; }
        public string UserID { get; set; }
        public string HarmonizedTarrif { get; set; }
        public string DeclaredValue { get; set; }
        public string CatlougDestination { get; set; }
        public string EDIPackCode { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemInventory_Customer> tblItemInventory_Customer { get; set; }
        public virtual tblItemMaster tblItemMaster { get; set; }
    }
}
