//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblItemMaster()
        {
            this.tblItemInventory_Customer = new HashSet<tblItemInventory_Customer>();
            this.tblItemSKUMasters = new HashSet<tblItemSKUMaster>();
        }
    
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public string ItemType { get; set; }
        public string ItemContent { get; set; }
        public string Brand { get; set; }
        public string Department { get; set; }
        public Nullable<double> Price { get; set; }
        public string Class { get; set; }
        public string HTSCode { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Dimensions { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> GrossLBs { get; set; }
        public Nullable<double> TareLBs { get; set; }
        public string Unit { get; set; }
        public Nullable<double> MaxTemprature { get; set; }
        public Nullable<double> MinTemprature { get; set; }
        public string TempratureUnit { get; set; }
        public string HSID { get; set; }
        public string HSNumber1 { get; set; }
        public string HSNumber2 { get; set; }
        public string HSNumber3 { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemInventory_Customer> tblItemInventory_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemSKUMaster> tblItemSKUMasters { get; set; }
    }
}
