//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLocation()
        {
            this.tblItemInventory_Customer = new HashSet<tblItemInventory_Customer>();
            this.tblWarehouseMasters = new HashSet<tblWarehouseMaster>();
        }
    
        public string LocationID { get; set; }
        public string LocationDesc { get; set; }
        public string Zone { get; set; }
        public string Class { get; set; }
        public string CubicDimensions { get; set; }
        public string TempratureRange { get; set; }
        public string UserRoleCode { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemInventory_Customer> tblItemInventory_Customer { get; set; }
        public virtual tblUserRole tblUserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWarehouseMaster> tblWarehouseMasters { get; set; }
    }
}
