//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderDetail
    {
        public string OrderID { get; set; }
        public string OrderDescription { get; set; }
        public string OrderType { get; set; }
        public string SourceID { get; set; }
        public string ShippingRateID { get; set; }
        public string ShippingAccountNumber { get; set; }
        public string EDI { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserRoleCode { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<bool> isEmailNotify { get; set; }
        public Nullable<int> BillingAddressID { get; set; }
        public Nullable<int> ShippingAddressID { get; set; }
        public string Notes { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual tblBillingAddress tblBillingAddress { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblOrderSource tblOrderSource { get; set; }
        public virtual tblShippingAddress tblShippingAddress { get; set; }
        public virtual tblShippingRatesMaster tblShippingRatesMaster { get; set; }
        public virtual tblUserProfile tblUserProfile { get; set; }
    }
}
