//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStorageLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStorageLocation()
        {
            this.tblItemInventory_Customer = new HashSet<tblItemInventory_Customer>();
        }
    
        public int LocationID { get; set; }
        public int WarehouseID { get; set; }
        public string LocationCode { get; set; }
        public string LocationDesc { get; set; }
        public string Zone { get; set; }
        public string Class { get; set; }
        public string CubicDimensions { get; set; }
        public string TempratureRange { get; set; }
        public string UserRoleCode { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemInventory_Customer> tblItemInventory_Customer { get; set; }
        public virtual tblWarehouseMaster tblWarehouseMaster { get; set; }
    }
}
