//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUserProfile()
        {
            this.tblUserSecurityGroups = new HashSet<tblUserSecurityGroup>();
        }
    
        public int UserID { get; set; }
        public int CustomerID { get; set; }
        public string UserName { get; set; }
        public string EncryptedPassword { get; set; }
        public int SecurityGroupID { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public bool isActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> WarehouseID { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblSecurityGroup tblSecurityGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserSecurityGroup> tblUserSecurityGroups { get; set; }
    }
}
